version: "3.8"
services:
  web:
    container_name: web
    build: .
    ports:
      - "8080:80"
    networks:
      - "net"
    environment:
      - VIRTUAL_PORT=80

networks:
  net:
    external:
      name: net
