version: "3.8"

services:
  reverse-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
    network-mode: bridge
    ports:
      - "80:80"
      - "443:443"

    nginx-proxy-acme:
      image: nginxproxy/acme-companion
      container_name: nginx-proxy-acme
      volumes-from:
        - nginx-proxy
      volumes:
        - certs:/etc/nginx/certs
        - acme:/etc/acme.sh
        - /run/docker.sock:/var/run/docker.sock:ro
      environment:
        - DEFAULT_EMAIL=travis@travish.com
      restart: always
      network-mode: bridge
  web:
    container_name: web
    build: .
    network_mode: bridge
    depends-on:
      - nginx-proxy-acme
    environment:
      - VIRTUAL_HOST=kiddspazz.com
      - LETSENCRYPT_HOST=kiddspazz.com
      - VIRTUAL_PORT=80


volumes:
  certs:
  html:
  vhost:
  dhparam:

networks:
  default:
    external:
      # the default network name is [parent-dir]_default, so in this case www_default
