version: "3.8"
services:
  web:
    container_name: web
    build: .
    network_mode: bridge
    environment:
      - VIRTUAL_HOST=kiddspazz.com
      - LETSENCRYPT_HOST=kiddspazz.com
      - VIRTUAL_PORT=80

networks:
  net:
    external:
      name: net
