version: "3.7"

services:
    nginx-proxy:
        image: "nginxproxy/nginx-proxy"
        container_name: "nginx-proxy"
        volumes:
            - "conf:/etc/nginx/conf.d"
            - "vhost:/etc/nginx/vhost.d"
            - "html:/usr/share/nginx/html"
            - "certs:/etc/nginx/certs:ro"
            - "/var/run/docker.sock:/tmp/docker.sock:ro"
        restart: "always"
        network_mode: "bridge"
        ports:
            - "80:80"
            - "443:443"

    acme-companion:
        image: "nginxproxy/acme-companion"
        container_name: "nginx-proxy-acme"
        volumes_from:
            - "nginx-proxy"
        volumes:
            - "certs:/etc/nginx/certs:rw"
            - "acme:/etc/acme.sh"
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
        network_mode: bridge
        environment:
            DEFAULT_EMAIL: "travis@travish.com"
        restart: "always"

volumes:
    conf:
    vhost:
    html:
    certs:
    acme:
