name: ci

on:
  push:
    branches:
      - 'dev'

jobs:
  deploy-new-web-app:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: kiddspazz/www_web:latest

      -
        name: Deploy reverse-proxy setup to kiddspazz.com
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          sync: true
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          script: |
            rm -rf tmp-docker
            mkdir tmp-docker
            cd tmp-docker
            wget https://raw.githubusercontent.com/kiddspazz/www/dev/reverse-proxy/docker-compose.yml
            docker stop letsencrypt-helper
            docker stop reverse-proxy
            docker rm letsencrypt-helper
            docker rm reverse-proxy
            docker network rm net
            docker network create net
            docker-compose up -d

      -
        name: Deploy to web app to kiddspazz.com
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          script: |
            docker pull kiddspazz/www_web
            docker stop web
            docker rm web
            docker run --rm --name web -e VIRTUAL_HOST=kiddspazz.com -e LETSENCRYPT_HOST=kiddspazz.com -e VIRTUAL_PORT=80 --network net -d kiddspazz/www_web
