name: production environment

on:
  push:
    branches:
      - 'main'

jobs:
  deploy-new-web-app:
    runs-on: ubuntu-latest
    steps:
      -
        name: Deploy web app to travish.com
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST_PROD }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME_PROD }}
          key: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          script: |
            docker pull kiddspazz/www_web
            docker stop web
            docker rm web
            docker stop www_web
            docker rm www_web
            docker run --rm --name web -e VIRTUAL_HOST=travish.com \
              -e LETSENCRYPT_HOST=travish.com -e VIRTUAL_PORT=80 \
              -d kiddspazz/www_web
            docker run --rm --name www_web -e VIRTUAL_HOST=www.travish.com \
              -e LETSENCRYPT_HOST=www.travish.com -e VIRTUAL_PORT=80 \
              -d kiddspazz/www_web
            docker rmi $(docker images --filter 'dangling=true' -q --no-trunc)
