name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  deploy-new-web-app:
    runs-on: ubuntu-latest
    steps:
      -
        name: Deploy reverse-proxy setup to travish.com
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST_PROD }}
          sync: true
          username: ${{ secrets.DIGITALOCEAN_USERNAME_PROD }}
          key: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN_PROD }}
          script: |
            rm -rf tmp-docker
            mkdir tmp-docker
            cd tmp-docker
            wget https://raw.githubusercontent.com/kiddspazz/www/dev/reverse-proxy/docker-compose-prod.yml
            docker stop letsencrypt-helper
            docker stop reverse-proxy
            docker rm letsencrypt-helper
            docker rm reverse-proxy
            docker network rm net
            docker network create net
            docker-compose up -d

      -
        name: Deploy to web app to travish.com
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST_PROD }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME_PROD }}
          key: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN_PROD }}
          script: |
            docker pull kiddspazz/www_web
            docker stop web
            docker rm web
            docker run --rm --name web -e VIRTUAL_HOST=travish.com -e LETSENCRYPT_HOST=travish.com -e VIRTUAL_PORT=80 --network net -d kiddspazz/www_web
